apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-service
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001  # Указываем конкретный порт для доступа снаружи. Диапазон допустимых портов по умолчанию: 30000-32767.
